export const GYM_DATE_CREATE_REQUEST = 'GYM_DATE_CREATE_REQUEST'; 
export const GYM_DATE_CREATE_SUCCESS = 'GYM_DATE_CREATE_SUCCESS'; 
export const GYM_DATE_CREATE_FAIL = 'GYM_DATE_CREATE_FAIL'; 

export const GYM_DATE_DETAILS_REQUEST = 'GYM_DATE_DETAILS_REQUEST'; 
export const GYM_DATE_DETAILS_SUCCESS = 'GYM_DATE_DETAILS_SUCCESS'; 
export const GYM_DATE_DETAILS_FAIL = 'GYM_DATE_DETAILS_FAIL'; 